using System;
using System.Collections.Generic;

namespace RythmRPG.Rhythm.Editing
{
    /// <summary>
    /// Loads a RhythmChart into a beat-based ChartSession and writes it back. Storage stays schema v1
    /// (seconds) so the runtime and the legacy composer keep working unchanged.
    /// Notes of unsupported types (Arrow, Cluster) are not shown in the session but are preserved on save.
    /// </summary>
    public static class ChartSessionBridge
    {
        public static ChartSession Load(RhythmChart chart, Action<string> warn = null)
        {
            var laneIds = new List<string>();
            for (int i = 0; i < chart.Lanes.Count; i++) laneIds.Add(chart.Lanes[i].Id);
            var session = new ChartSession(chart.CreateTempoMap(), laneIds);
            session.SnapEnabled = chart.SnapEnabled;
            session.SnapDivision = (int)chart.SnapDivision;
            // Notes generated by a pattern are not editable on their own: they are rebuilt from the pattern on save.
            var manual = new List<RhythmNoteData>();
            for (int i = 0; i < chart.Notes.Count; i++)
            {
                if (chart.Notes[i] != null && !PatternExpander.IsGenerated(chart.Notes[i].Metadata)) manual.Add(chart.Notes[i]);
            }

            session.Load(NoteMigration.ToInstances(manual, session.Tempo, warn), chart.Patterns);
            return session;
        }

        /// <summary>Rewrites chart.Notes from the session. Existing note objects are reused (keeps fields the session does not model).</summary>
        public static void Apply(ChartSession session, RhythmChart chart)
        {
            var existing = new Dictionary<string, RhythmNoteData>();
            var preserved = new List<RhythmNoteData>();
            for (int i = 0; i < chart.Notes.Count; i++)
            {
                RhythmNoteData n = chart.Notes[i];
                if (n == null || PatternExpander.IsGenerated(n.Metadata)) continue; // regenerated from patterns below
                if (NoteMigration.DefinitionIdFor(n.NoteType) == null) preserved.Add(n);
                else existing[n.Id] = n;
            }

            var result = new List<RhythmNoteData>();
            IList<NoteInstance> instances = session.Notes;
            for (int i = 0; i < instances.Count; i++)
            {
                NoteInstance inst = instances[i];
                RhythmNoteData target;
                if (!existing.TryGetValue(inst.Id, out target))
                {
                    target = new RhythmNoteData(inst.LaneId, 0d, NoteMigration.LegacyTypeFor(inst.DefinitionId));
                    target.AssignId(inst.Id);
                }

                RhythmNoteDefinition def = chart.FindDefinition(NoteMigration.LegacyTypeFor(inst.DefinitionId));
                NoteMigration.ApplyToLegacy(inst, session.Tempo, target, def);
                result.Add(target);
            }

            // Programmed patterns: regenerate their notes from the pattern parameters.
            IList<PatternInstance> patterns = session.Patterns;
            for (int p = 0; p < patterns.Count; p++)
            {
                List<NoteInstance> generated = PatternExpander.Expand(patterns[p], session.LaneIds);
                for (int i = 0; i < generated.Count; i++)
                {
                    NoteInstance inst = generated[i];
                    var target = new RhythmNoteData(inst.LaneId, 0d, NoteMigration.LegacyTypeFor(inst.DefinitionId));
                    target.AssignId(inst.Id);
                    RhythmNoteDefinition def = chart.FindDefinition(NoteMigration.LegacyTypeFor(inst.DefinitionId));
                    NoteMigration.ApplyToLegacy(inst, session.Tempo, target, def);
                    result.Add(target);
                }
            }

            chart.Patterns.Clear();
            for (int p = 0; p < patterns.Count; p++) chart.Patterns.Add(patterns[p].Clone());

            result.Sort((a, b) => a.HitTime.CompareTo(b.HitTime));
            chart.Notes.Clear();
            chart.Notes.AddRange(result);
            chart.Notes.AddRange(preserved);
        }
    }
}
